### ISSUE TITLE
Possibility to combine with immer

### ISSUE THREAD

**Issue by SirWindfield** [arnelenero/react-entities#4]
Hey!
I really enjoy this library as a smaller cousin of the whole state management issue :smile:
I noticed that Redux does allow the usage of [immer](https://github.com/immerjs/immer) using their [Redux starter kit](https://redux-starter-kit.js.org/introduction/quick-start). I think that it would fit great as well into this library. So, instead of mutating using `setState` and passing a new state to it the library would provide the state itself and users can modify that.

**Comment by arnelenero** [comment]
Hi. I find your idea very interesting. This might simplify things even further. Now I'm thinking of the possible resulting syntax of this.

**Comment by arnelenero** [comment]
After further consideration, I realized that introducing Immer-style state changes in react-entities actions may pose issues because:

- Async actions allow updating the state at any point in the flow, before `await` calls, and after. Passing an Immer-style state "draft" will not be able to control when the state will be replaced by the draft.
- Immer's produce() will add some performance hit, maybe not significant but still not zero.
- If you have to update a lot of properties of the entity state, doing a lot of individual `state.xxxxx = val` can be more cumbersome than just a single `setState({ . . . })`.

We have to weigh this against what possible advantages we can get out of doing this. Other than syntax eyecandy, what other benefits do you see?

**Comment by arnelenero** [comment]
Closing this issue as the suggestion has been carefully considered but does not appear to be feasible at this time, as explained in the comment above. Further discussion on the matter is most welcome.
